# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - "v*.*"
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Get version
        run: |
          version="$(cat ./version.txt)"
          echo "Version.txt: $version"
          
      - name: Zip
        run: |
          cd ../
          rm -rf cacawpack.zip
          zip -r cacawpack.zip mc-cacawpack -x ".git/*" ".github/*" "scripts/*"
          mv cacawpack.zip mc-cacawpack/
        if: startsWith(github.ref, 'refs/tags/')

      - name: list files
        run: |
          ls ./
          echo "---"
          ls ../

      - name: Release with version tag
        uses: softprops/action-gh-release@v2
        with:
          files: cacawpack.zip
        if: startsWith(github.ref, 'refs/tags/')

      # - name: Release with latest tag
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: cacawpack-$version.zip
      #     tag_name: 'latest'
